pipeline {
	agent any
	stages {

		stage('Create kubernetes cluster') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-capstone') {
					sh '''
eksctl create cluster \
--name capstonecluster \
--version 1.18 \
--region us-west-2 \
--nodegroup-name linux-nodes \
--node-type t2.small \
--nodes 3 \
--nodes-min 1 \
--nodes-max 4 \
--zones us-west-2a \
--zones us-west-2b \
--ssh-access \
--ssh-public-key ekskey \
--managed
					'''
				}
			}
		}

		

		stage('Create conf file cluster') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-capstone') {
					sh '''
						aws eks --region us-west-2 update-kubeconfig --name capstonecluster
					'''
				}
			}
		}

	}
}
