---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycapstoneapp-service
  namespace: mlapp4ms
  labels:
    app: mycapstoneapp
spec:
  selector:
    matchLabels:
      app: mycapstoneapp
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: mycapstoneapp
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: capstone
        image: msoulie/capstone-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          successThreshold: 1
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mycapstoneapp-service
  namespace: mlapp4ms
spec:
  selector:
    app: mycapstoneapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80