Description: >
    Maxime Soulie - 2020
    Deploy a Jenkins Server using Cloudformation.

Parameters:
  EnvironmentName:
    Description: 'Environment name, used as a prefix for resources'
    Type: String
  WhitelistedIP:
    Description: Whitelisted IP for SSH connection
    Type: String
  KeyPair:
    Description: KeyPair name to access host via SSH
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: udabuntu

Resources:
  JenkinsEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-06e54d05255faf8f6 
      InstanceType: t2.micro
      SecurityGroupIds:
        - Ref: JenkinsSecurityGroup
      KeyName: !Sub '${KeyPair}'
      UserData:
        Fn::Base64: !Sub |
          #!/usr/bin/env bash
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
          sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          sudo apt update
          sudo apt upgrade -y
          sudo apt install openjdk-8-jdk -y
          sudo apt install jenkins -y
update          sudo apt install awscli -y

  JenkinsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH access via port 22 and Jenkins on port 8080
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub '${WhitelistedIP}'
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: !Sub '${WhitelistedIP}'